### PR TITLE
Added greetings action

### LINKED ISSUE #15: Add a greeting action
Greet only first time contributers to the project with links to our socials and discord.

### PR DESCRIPTION
**Pull request by ashwinexe**
Greets users on creating their new issue/PR in this repo

Closes #15

### CODE REVIEW

**Comment by ashwinexe** [comment]
@kaiwalyakoparkar review when available

**Comment by ashwinexe** [comment]
image

**Comment by kaiwalyakoparkar** [comment]
Did you add space after `our` and `youtube`?

**Comment by ashwinexe** [comment]
@kaiwalyakoparkar yes, I've fixed that but unable to reproduce a new PR since I already created one

**Comment by ashwinexe** [comment]
@Kaiwalya Koparkar#0747 I took a dive into why I wasn't able to change the behavior of gh action to *run every time instead of just first time*, turns out it's hardcoded in the script of `first-interaction` GitHub maintains for everyone. 
Now I can fork this and customize the ts, making it our own custom action lol but the use to customize seems pretty low (just to check the output of action we want)

Here's the [snippet](https://github.com/actions/first-interaction/blob/main/src/main.ts) from the [action](c) we use 👇️
image

**Review by AnuragThePathak — APPROVED** [review]

**Comment by AnuragThePathak** [comment]
@ashwinexe  Your main branch didn't contain a a space between "our" and the anchor tag. So it was showing outdated results.

**Pull request merged**
